//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class IadAvarTbl
    {
        public long ID { get; set; }
        public string TitleActivity { get; set; }
        public string PersianStartDate { get; set; }
        public string PersianStartTime { get; set; }
        public Nullable<System.DateTime> StartDateTime { get; set; }
        public string PersianEndTime { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
        public string ReminderCategory { get; set; }
        public string description { get; set; }
        public Nullable<int> PeriodNumBer { get; set; }
        public Nullable<bool> Periodic { get; set; }
        public Nullable<System.DateTime> PeriodicEndTime { get; set; }
        public string PeriodocKind { get; set; }
        public Nullable<int> MeasurePeriodic { get; set; }
        public string EndDesription { get; set; }
    }
}
