//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class SabteHazinehSakhtemanTbl
    {
        public long ID { get; set; }
        public string TitleCost { get; set; }
        public Nullable<System.DateTime> GDate { get; set; }
        public string PersianDate { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string mmonth { get; set; }
        public string ShiveTaghsim { get; set; }
        public string Description { get; set; }
        public Nullable<int> IDVahed { get; set; }
        public string Year { get; set; }
        public Nullable<decimal> Income { get; set; }
        public string VahedName { get; set; }
        public Nullable<System.DateTime> StartGdat { get; set; }
        public string startPersianDate { get; set; }
        public Nullable<System.DateTime> FinishGdate { get; set; }
        public string FinishPersianDate { get; set; }
        public Nullable<bool> Enteghali { get; set; }
    }
}
