//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepositTbl
    {
        public long ID { get; set; }
        public string Deposit { get; set; }
        public Nullable<long> ssum { get; set; }
        public string PersianDate { get; set; }
        public Nullable<System.DateTime> GDate { get; set; }
        public string description { get; set; }
    }
}
