//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialTbl
    {
        public long ID { get; set; }
        public string Title { get; set; }
        public Nullable<decimal> Income { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string PersianDate { get; set; }
        public Nullable<System.DateTime> Datee { get; set; }
        public string Description { get; set; }
        public string FinancialCategory { get; set; }
        public string Deposite { get; set; }
        public Nullable<bool> Pas { get; set; }
        public string girandeh { get; set; }
        public Nullable<System.DateTime> EnterDate { get; set; }
        public Nullable<decimal> Meghdar { get; set; }
        public string Takhsis { get; set; }
        public Nullable<int> IntPersianYear { get; set; }
        public Nullable<int> IntPersianMonth { get; set; }
    }
}
