//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class GhazaBarnamehTbl
    {
        public long ID { get; set; }
        public string Onvan { get; set; }
        public Nullable<int> Nafar { get; set; }
        public Nullable<System.DateTime> Gdate { get; set; }
        public string KasrMavad { get; set; }
        public Nullable<decimal> Gheimat { get; set; }
        public string PersainDate { get; set; }
        public string Vade { get; set; }
    }
}
