//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class IadAvarDaroTbl
    {
        public long ID { get; set; }
        public string OnvanDaro { get; set; }
        public string PersianDate { get; set; }
        public string Tozihat { get; set; }
        public Nullable<System.DateTime> GDate { get; set; }
        public Nullable<System.DateTime> Saat { get; set; }
        public Nullable<int> Dore { get; set; }
        public Nullable<int> Dafe { get; set; }
        public string NoeDore { get; set; }
    }
}
