//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class MavadGhzaNameTbl
    {
        public long ID { get; set; }
        public string NameGhaza { get; set; }
        public string NameMavad { get; set; }
        public Nullable<int> Meghdar { get; set; }
        public string Vahed { get; set; }
    }
}
