//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnvanVamTbl
    {
        public long ID { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> StarGdate { get; set; }
        public string StartPersianDate { get; set; }
        public Nullable<bool> FAAL { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> MablaghVam { get; set; }
        public Nullable<decimal> MablaghGhest { get; set; }
        public Nullable<int> TedadAghsat { get; set; }
    }
}
