//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class PardakhtVamTbl
    {
        public long ID { get; set; }
        public string OnvanVam { get; set; }
        public string NameVamGirandeh { get; set; }
        public Nullable<decimal> MablaghPardakhti { get; set; }
        public string Tozihat { get; set; }
        public Nullable<System.DateTime> GTarikh { get; set; }
        public string Tarikh { get; set; }
    }
}
