//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class TreeKala
    {
        public long ID { get; set; }
        public string Header { get; set; }
        public string SubHeader { get; set; }
        public string SubSubHeader { get; set; }
        public string Vahed { get; set; }
        public Nullable<decimal> IekCallery { get; set; }
        public string description { get; set; }
    }
}
