//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyManager
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FamilyManaerDBEntities : DbContext
    {
        public FamilyManaerDBEntities()
            : base("name=FamilyManaerDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ComboBoxTbl> ComboBoxTbls { get; set; }
        public virtual DbSet<DepositTbl> DepositTbls { get; set; }
        public virtual DbSet<FinancialTbl> FinancialTbls { get; set; }
        public virtual DbSet<GhazaBarnamehTbl> GhazaBarnamehTbls { get; set; }
        public virtual DbSet<GhzaNameTbl> GhzaNameTbls { get; set; }
        public virtual DbSet<HamsaieTbl> HamsaieTbls { get; set; }
        public virtual DbSet<IadAvarDaroTbl> IadAvarDaroTbls { get; set; }
        public virtual DbSet<IadAvarTbl> IadAvarTbls { get; set; }
        public virtual DbSet<MavadGhzaNameTbl> MavadGhzaNameTbls { get; set; }
        public virtual DbSet<MojodiKalaTbl> MojodiKalaTbls { get; set; }
        public virtual DbSet<OnvanDaramadTbl> OnvanDaramadTbls { get; set; }
        public virtual DbSet<OnvanVamNafarTbl> OnvanVamNafarTbls { get; set; }
        public virtual DbSet<OnvanVamTbl> OnvanVamTbls { get; set; }
        public virtual DbSet<PardakhtVamTbl> PardakhtVamTbls { get; set; }
        public virtual DbSet<SabteHazinehSakhtemanTbl> SabteHazinehSakhtemanTbls { get; set; }
        public virtual DbSet<TakhsisDaramadKhoshe> TakhsisDaramadKhoshes { get; set; }
        public virtual DbSet<TakhsisVamTbl> TakhsisVamTbls { get; set; }
        public virtual DbSet<TanzimZamanIadAvar> TanzimZamanIadAvars { get; set; }
        public virtual DbSet<TreeKala> TreeKalas { get; set; }
        public virtual DbSet<VAMTbl> VAMTbls { get; set; }
    }
}
