//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class TanzimZamanIadAvar
    {
        public Nullable<System.DateTime> saat { get; set; }
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Hafteh { get; set; }
        public Nullable<int> rooz { get; set; }
        public byte[] aks { get; set; }
        public Nullable<bool> font { get; set; }
        public string Passage { get; set; }
    }
}
