//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class HamsaieTbl
    {
        public long ID { get; set; }
        public string NameVahed { get; set; }
        public Nullable<int> TedadNafarat { get; set; }
        public Nullable<int> Metrazh { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> StartGdate { get; set; }
        public string startPersianDate { get; set; }
        public Nullable<System.DateTime> FinishGdate { get; set; }
        public string FinishPersianDate { get; set; }
        public Nullable<bool> Tasfieh { get; set; }
        public string PhineNumber { get; set; }
    }
}
